config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :new, :create, :update, :show, :destroy] do
      get "checkout", to: 'orders#edit',as: :checkout
  end
  resources :restaurants, only: [:new, :create]
  resources :ingredients
  get "my_cart", to: 'orders#new'
  # post "my_cart", to: 'orders#create'
  # get "checkout", to: 'orders#edit',as: :checkout
  get "my_cart/success", to: 'orders#success'
  # Restaurant routes
  get "my_ingredients", to: 'ingredients#my_ingredients'
  get "my_orders", to: 'orders#my_orders'
  get "dashboard", to: 'restaurants#dashboard'
  get "shop_settings", to: 'restaurants#settings'

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/shared/_carbon_perf.html.erb
<%# Section header %>
<div class="dashboard-page-header d-flex justify-content-between mt-5">
  <h1>Carbon performance</h1>
</div>
<%# Content %>
<div class="carbon-sum justify-content-between">
  <div class="label">
    <h4>So far, you’ve decreased carbon emission</h4>
    <%= link_to 'See how we calculate the emission', '#' %>
  </div>
  <div class="lable-right d-flex">
    <%= image_tag 'tree-large.svg', class: "mr-2" %>
    <h1 class="mr-2"><%= number_with_delimiter(@co2, :delimiter => ',') %> kg</h1>
  </div>
</div>

app/views/shared/_card-d-green.html.erb
<div class="card-d-green">
  <h2>CO2 emission saved: </h2>
  <p><%= @ingredient.stock_amount * 2.54 %> kg</p>
</div>

app/views/shared/_card-frame1.html.erb
<%# <div class="card-frame1" style="background-image: url(<%= asset_path('deal-01.png') %>
<%# <p class="head">20% off for all</p>
  <p>Use code NOMOFIRSTTIME to get your <br>
     first
    order on demand</p> %>
<%# </div> %>
<%= image_tag "deal-03.svg" %>

app/views/shared/_card-green.html.erb
<div class="card-green">
  <h2>Total weight: </h2>
  <p><strong><%= @ingredient.stock_amount%> kg</strong></p>
</div>

app/views/shared/_card-l-green.html.erb
<div class="card-l-green">
  <h2>Expiry date: </h2>
  <p><strong><%= @ingredient.expiry_date.strftime("%d %b") %></strong></p>
</div>

app/views/shared/_card-recipe.html.erb
<% @recipe_hashes.each do |recipe_hash| %>
  <div class="card-column card-recipe">
    <%= link_to recipe_hash[:link], action: 'go' do %>
      <%#= image_tag recipe_hash[:src], alt: "alttext" %>
      <%#= cl_image_tag recipe.photo.key, class: "image" %>
      <div class="card-recipe-info">
        <div class="card-recipe-text">
          <div class="text-head">
            <%= image_tag "Review-star.svg", alt: "review-star", width: "24px" %>
            <p><%= recipe_hash[:review] %></p>
          </div>
          <div class="text-body">
            <h2><%= recipe_hash[:name] %></h2>
          </div>
          <div class="text-foot">
            <p><%= recipe_hash[:time] %>・<%= recipe_hash[:num_of_ingredients] %> ingredients</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_cart_sidebar.html.erb
<%# Sidenav %>
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%# Order in Sidebar %>
  <div id="main">
    <h4 class="my-cart mb-4">My Cart</h4>
    <% if current_user.pending_order.present?  %>
      <% current_user.pending_order.ingredients.each do |ingredient| %>
        <div class="cart-item d-flex justify-content-between mb-3">
          <div class="cart-detail d-flex align-middle">
            <%= cl_image_tag ingredient.photo.key, class: "cart-img" %>
            <div class="item-price">
              <p class="mb-0" style="font-size: 16px; font-weight: 600;"><%= ingredient.stock_amount %><%= ingredient.unit.downcase %>x <%= ingredient.name %></p>
              <p class="cart-resto mt-1"><%= ingredient.seller.restaurant.name %></p>
              <%# Remove %>
            </div>
          </div>
          <p mb-0><%= humanized_money_with_symbol(ingredient.price * ingredient.stock_amount) %></p>
        </div>
      <% end %>
      <%= link_to order_checkout_path(current_user.pending_order), class: "btn btn-checkout bg-black mt-4" do %>
        <p>Checkout</p>
        <p>$<%= current_user.order_total_price %></p>
      <% end %>
    <% else %>
      <%= "Cart is empty" %>
    <% end %>
  </div>
</div>
<%# Cart Icon %>
<span style="cursor:pointer" onclick="openNav()" class="m-2">
  <div class="cart-number d-flex">
    <%= image_tag "icon_cart.svg" %>

    <% if current_user.pending_order.nil? || current_user.pending_order.ingredients.count == 0 %>
      <p>0</p>
    <% else %>
      <p><%= current_user.pending_order.ingredients.count %></p>
    <% else %>
      <p>0</p>
    <% end %>
  </div>
</span>
<script>
  // /* Set the width of the side navigation */
    function openNav() {
      document.getElementById("mySidenav").style.width = "340px";
      // document.getElementById("mySidenav").style.display = "block";
  
    }
    // /* Set the width of the side navigation to 0 */
    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
      // document.getElementById("mySidenav").style.display = "none";
    }
    const urlParams = new URLSearchParams(window.location.search);
    const cartStatus = urlParams.get('cart');
    if (cartStatus === "open") {
      openNav();
    };
</script>

app/views/shared/_checkout_navbar.html.erb
<div class="checkout-navbar">
  <%= link_to :back do %>
    <%= image_tag "arrow-left.svg", alt: "back", class: "back" %>
  <% end %>
  Checkout
</div>

app/views/shared/_dashboard_sidenav.html.erb
<div class="dashboard-sidenav">
  <%# Logo + Hambuger %>
  <div class="sidebar-item justify-content-between d-flex mt-2">
    <%= image_tag 'nomo-logo-black.svg', id: "nomo-b-logo"%>
    <%= image_tag 'bars.svg'%>
  </div>
  <%# Shop name %>
  <div class="shop-name mt-4" style="font-weight: 600;">
    <hr class="sidenav-divider">
    <%= @shop_name %>
    <hr class="sidenav-divider">
  </div>
  <%# Sidenav Menu %>
  <ul>
    <%# Home %>
    <%= link_to dashboard_path do %>
      <li class="sidenav-item d-flex">
        <%= image_tag 'home-outline.svg', id: "nomo-b-logo", class: "mr-2"%>
        <span class="menu-title">Home</span>
      </li>
    <% end %>
    <%# Ingredients %>
    <%= link_to my_ingredients_path do %>
      <li class="sidenav-item d-flex">
        <%= image_tag 'Tree.svg', id: "nomo-b-logo", class: "mr-2"%>
        <span class="menu-title">Ingredients</span>
      </li>
    <% end %>
    <%# Orders %>
    <%= link_to my_orders_path do %>
      <li class="sidenav-item d-flex">
        <%= image_tag 'icon_cart.svg', id: "nomo-b-logo", class: "mr-2"%>
        <span class="menu-title">Orders</span>
      </li>
    <% end %>
    <%# Setting %>
    <%= link_to shop_settings_path do %>
      <li class="sidenav-item d-flex">
        <%= image_tag 'Gear.svg', id: "nomo-b-logo", class: "mr-2"%>
        <span class="menu-title">Store settings</span>
      </li>
    <% end %>
    <%# Donate banner %>
    <li class="donate">
      <div id="donate-banner" style="background-image: url(<%= asset_path('donate-banner.svg') %>);">
        <p><strong>Donate your product to local food banks</strong></p>
        <div class="d-flex item">
          <p style="font-size: 14px;">Get started</p>
          <%= image_tag 'arrow-right-small.svg', id: "nomo-b-logo", class: "ml-2"%>
        </div>
      </div>
    </li>
    <%# Back to NOMO %>
    <%= link_to ingredients_path do %>
      <li class="sidenav-item d-flex">
        <%= image_tag 'arrow-out.svg', id: "nomo-b-logo", class: "mr-2"%>
        <span class="menu-title">Back to Nomo</span>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ingredient_table_head.html.erb
<thead>
  <tr class="table-primary">
    <th scope="col" class="table-primary pl-0"></th>
    <!-- <th scope="col" class="table-primary pl-2 pr-0"></th> -->
    <th scope="col" class="table-primary">ID</th>
    <th scope="col" class="table-primary">Name</th>
    <th scope="col" class="table-primary">Unit price</th>
    <th scope="col" class="table-primary">Qty</th>
    <th scope="col" class="table-primary">Unit</th>
    <th scope="col" class="table-primary">Discount(%)</th>
    <%# <th scope="col" class="table-primary">Category</th> %>
    <th scope="col" class="table-primary">Expiry date</th>
  </tr>
</thead>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%# Logo %>
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'Nomo_logo.png', width:"88px" %>
  <% end %>
  <%# Dropdown trigger %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%# Right actions %>
  <div class="navbar-actions">
    <%# Search %>
    <div class="nav-item">
      <%= form_tag ingredients_path, method: :get do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search"
          %>
        <%= submit_tag "", style: "display: none;" %>
      <% end %>
    </div>
    <%# For business %>
    <div class="nav-item active">
      <%= link_to "For business", "#", class: "nav-link" %>
    </div>
    <%# Cart %>
    <div class="nav-item mr-0">
      <%= render 'shared/cart_sidebar' if user_signed_in? %>
    </div>
    <%# Dropdown %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%# Avatar %>
        <li class="nav-item dropdown">
          <% if user_signed_in? && current_user.restaurant.present? %>
            <%= image_tag "nomo_default_avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%# Dropdown List : Buyer%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%# Username %>
              <div class="user-name">
                <p class="username"><%= current_user.name %></p>
                <p class="email"><%= current_user.email %></p>
              </div>
              <%# Icon + List %>
              <%= link_to orders_path, class: "dropdown-item icon mt-2" do %>
                <%= image_tag "Tree.svg", alt: "my-order" %>My orders
              <% end %>
              <%= link_to "#", class: "dropdown-item icon" do %>
                <%= image_tag "Heart.svg", alt: "my-wishlist" %>My wishlist
              <% end %>
              <%= link_to "#", class: "dropdown-item icon" do %>
                <%= image_tag "PencilLine.svg", alt: "my-account" %>Account settings
              <% end %>
              <p class="business">BUSINESS</p>
              <%= link_to dashboard_path, class: "dropdown-item icon", target: :_blank do %>
                <%= image_tag "store.svg", alt: "my-account" %>Manage store
              <% end %>
              <%= link_to shop_settings_path, class: "dropdown-item icon" do %>
                <%= image_tag "Gear.svg", alt: "my-account" %>Store settings
                <hr>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item icon" do %>
                <%= image_tag "ArrowRight.svg", alt: "log-out" %>Log out
              <% end %>
            </div>
          <% elsif user_signed_in? %>
            <%= image_tag "nomo_default_avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%# DropdownList : Not Login%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%# Icon + List %>
              <%= link_to orders_path, class: "dropdown-item icon" do %>
                <%= image_tag "Tree.svg", alt: "my-order" %>My orders
              <% end %>
              <%= link_to "#", class: "dropdown-item icon" do %>
                <%= image_tag "Heart.svg", alt: "my-wishlist" %>My wishlist
              <% end %>
              <%= link_to "#", class: "dropdown-item icon" do %>
                <%= image_tag "PencilLine.svg", alt: "my-account" %>Account settings
              <% end %>
              <%= link_to new_restaurant_path, class: "dropdown-item icon" do %>
                <%= image_tag "store.svg", alt: "my-order" %>Become a seller
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item icon" do %>
                <%= image_tag "ArrowRight.svg", alt: "log-out" %>Log out
              <% end %>
            </div>
          <% else %>
            <%= image_tag "nomo_default_avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%# DropdownList : Not Login%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%# Icon + List %>
              <%= link_to new_user_registration_path, class: "dropdown-item icon" do %>
                <%= image_tag "HandWaving.svg", alt: "sign-up" %>Sign up
              <% end %>
              <%= link_to user_session_path, class: "dropdown-item icon" do %>
                <%= image_tag "Key.svg", alt: "log-in" %>Log in
              <% end %>
              <%= link_to "#", class: "dropdown-item icon" do %>
                <%= image_tag "Question.svg", alt: "help" %>Help
              <% end %>
            </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_shop_score.html.erb
<%# Section header %>
<div class="dashboard-page-header d-flex justify-content-between mt-5">
  <h1>Analytic</h1>
</div>
<%# Content %>
<%# Rank banner %>
<div class="carbon-sum justify-content-between" style="height: 96px;">
  <div class="left-panel d-flex">
    <div class="rank-large">
      <h4>56</h4>
    </div>
    <div class="label">
      <p class="mb-0">Overall green score</p>
      <h4>Rank <span class="text-highlight">#126</span> from <span class="text-highlight">344</span> local shops</h4>
    </div>
  </div>
  <div class="label">
    What is a green score?
  </div>
</div>
<%# Suggest action + Nearby score %>
<div class="panel-container d-flex mt-4">
  <%# Suggest action %>
  <div class="suggest-action-container">
    <h4 class="mb-4">Suggested greener actions</h4>
    <div class="container d-flex flex-wrap p-0">
      <%# Actions %>
      <div class="green-action mr-3 mb-3">
        <div class="rank-rectangle">
          <h3>+$32</h3>
        </div>
        <p style="font-weight: 600;" class="mb-1 mt-2">Try decreasing overall tomato consumption by 5%</p>
        <p style="color: rgba(0, 0, 0, 0.6);">You will save $32 / month and prevent <br>
          40kg of CO2</p>
      </div>
      <div class="green-action mb-3">
        <div class="rank-rectangle">
          <h3>-18kg</h3>
        </div>
        <p style="font-weight: 600;" class="mb-1 mt-2">List seafood on the market 1 day earlier</p>
        <p style="color: rgba(0, 0, 0, 0.6);">Customers will be more likely to buy and you will waste less! Reduce 18kg of your CO2 footprint!</p>
      </div>
      <div class="green-action mr-3">
        <div class="rank-rectangle">
          <h3>+$45</h3>
        </div>
        <p style="font-weight: 600;" class="mb-1 mt-2">Order 18% less lettuce!</p>
        <p style="color: rgba(0, 0, 0, 0.6);">You will waste 10kg less per month! <br>
          and save $45</p>
      </div>
      <div class="green-action">
        <div class="rank-rectangle">
          <h3>🤣</h3>
        </div>
        <p style="font-weight: 600;" class="mb-1 mt-2">Adjust your fruit orders on Friday!</p>
        <p style="color: rgba(0, 0, 0, 0.6);">You usually order too many bananas!<br>
          Haste makes waste! Don't be a wiener. <br>
          Be a winner!</p>
      </div>
    </div>
  </div>
  <%# Nearby score %>
  <div class="nearby-score-container">
    <%# Header%>
    <div class="d-flex justify-content-between">
      <h4 class="mb-4">Nearby shops</h4>
      <span style="font-size: 14px;"><%= link_to 'View all', "#" %></span>
    </div>
    <%# Score list %>
    <div class="score-list">
      <div class="rank-small bg-d-green">
        <h4>87</h4>
      </div>
      <div class="label">
        <p class="mb-0" style="font-size: 16px; font-weight: 600;">Rank #34</p>
        <p class="mb-0"><%= Faker::Restaurant.name %></p>
      </div>
    </div>
    <div class="score-list">
      <div class="rank-small">
        <h4>58</h4>
      </div>
      <div class="label ">
        <p class="mb-0" style="font-size: 16px; font-weight: 600;">Rank #90</p>
        <p class="mb-0"><%= Faker::Restaurant.name %></p>
      </div>
    </div>
    <div class="score-list">
      <div class="rank-small bg-l-green" style="background-color: $nm-l-green;">
        <h4>45</h4>
      </div>
      <div class="label">
        <p class="mb-0" style="font-size: 16px; font-weight: 600;">Rank #123</p>
        <p class="mb-0"><%= Faker::Restaurant.name %></p>
      </div>
    </div>
    <div class="score-list">
      <div class="rank-small bg-yellow">
        <h4>32</h4>
      </div>
      <div class="label">
        <p class="mb-0" style="font-size: 16px; font-weight: 600;">Rank #238</p>
        <p class="mb-0"><%= Faker::Restaurant.name %></p>
      </div>
    </div>
    <div class="score-list mb-0">
      <div class="rank-small bg-orange" style="background-color: $nm-orange;">
        <h4>12</h4>
      </div>
      <div class="label">
        <p class="mb-0" style="font-size: 16px; font-weight: 600;">Rank #457</p>
        <p class="mb-0"><%= Faker::Restaurant.name %></p>
      </div>
    </div>
  </div>
</div>