config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :new, :create, :update, :show, :destroy] do
      get "checkout", to: 'orders#edit',as: :checkout
  end
  resources :restaurants, only: [:new, :create]
  resources :ingredients
  get "my_cart", to: 'orders#new'
  # post "my_cart", to: 'orders#create'
  # get "checkout", to: 'orders#edit',as: :checkout
  get "my_cart/success", to: 'orders#success'
  # Restaurant routes
  get "my_ingredients", to: 'ingredients#my_ingredients'
  get "my_orders", to: 'orders#my_orders'
  get "dashboard", to: 'restaurants#dashboard'
  get "shop_settings", to: 'restaurants#settings'

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :seller, class_name: "User", foreign_key: :seller_id
  has_one_attached :photo
  enum status: { sold: 0, unsold: 1 }
  enum public_status: { unavailable: 0, available: 1 }

  monetize :price_cents

  validates :name, :unit_price, :expiry_date, :unit, :stock_amount, :price_cents, presence: true
  attribute :public_status, :integer, default: 1
  attribute :status, :integer, default: 1
end

app/controllers/ingredients_controller.rb
require 'nokogiri'
require 'open-uri'
require 'date'

class IngredientsController < ApplicationController
  before_action :find_ingredient, only: [:show, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @all_ingredients = policy_scope(Ingredient.where(status: 1, public_status: 1))
    @all_six_ing = @all_ingredients.first(6)

    @restaurants = Restaurant.near(current_user.address, 10)
    @near_ingredients = []
    @restaurants.each do |restaurant|
      @near_ingredients << policy_scope(restaurant.ingredients_for_sale)
    # @ingredients << restaurant.users.first.ingredients_as_seller
    end
    @near_ingredients = @near_ingredients.flatten.first(3)

    @expire_today_ingredients = policy_scope(Ingredient.where(status: 1, public_status: 1).where(expiry_date: Date.today..Date.tomorrow))
    @expire_today_three_ing = @expire_today_ingredients.first(3)
    if params[:query].present?
      @ingredients = Ingredient.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @ingredients = Ingredient.all
    end
  end

  def my_ingredients
    @ingredients = Ingredient.where(seller_id: current_user.id).where("expiry_date >= ?", Date.today).reverse_order
    @expired_ingredients = Ingredient.where(seller_id: current_user.id).where("expiry_date < ?", Date.today).reverse_order
    @sold_ingredients = Ingredient.where(seller_id: current_user, status: :sold)
    @shop_name = current_user.restaurant.name
    authorize @ingredients
  end

  def new
    @ingredient = Ingredient.new
    @shop_name = current_user.restaurant.name
    authorize @ingredient
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    authorize @ingredient
    @ingredient.seller = current_user
    if @ingredient.save
      redirect_to my_ingredients_path
    else
      render :new
    end
  end

  def show
    @seller_ingredients = Ingredient.where(seller: @ingredient.seller).sample(3)
    @paired_ingredients = Ingredient.all.sample(3)
    @restaurant = @ingredient.seller.restaurant
    @marker = {
        lat: @restaurant.latitude,
        lng: @restaurant.longitude
    }
    @order = current_user.pending_order || Order.new

    ingredient = @ingredient.name
    url = "https://www.allrecipes.com/search/results/?search=#{ingredient}"
    html_file = URI.open(url).read
    html_doc = Nokogiri::HTML(html_file)

    @recipe_hashes = []

    html_doc.search('.card__title').first(3).each do |element|
      @name = element.text.strip
      @recipe_hashes << { name: @name }
    end

    html_doc.search('.card__titleLink').first(3).each_with_index do |ele, index|
      @recipe_hashes[index][:link] = ele.attribute('href').value
      html_file_for_recipe = URI.open(@recipe_hashes[index][:link]).read
      html_file_for_recipe_doc = Nokogiri::HTML(html_file_for_recipe)
      @recipe_hashes[index][:time] = html_file_for_recipe_doc.search('.recipe-meta-item-body')[2].text.strip
      @recipe_hashes[index][:num_of_ingredients] = html_file_for_recipe_doc.search('.ingredients-item').count
    end

    html_doc.search('.review-star-text').first(3).each_with_index do |ele, index|
      @recipe_hashes[index][:review] = ele.children.first.text.split(" ")[1]
    end

    html_doc.search('.card__authorName').first(3).each_with_index do |ele, index|
      @recipe_hashes[index][:author] = ele.text.strip
    end
  end

  def edit

  end

  def update
    if current_user.pending_order.present?
      @order = current_user.pending_order
    else
      @order = Order.create(buyer: current_user, status: :pending, total_price: 0)
    end
    @ingredient.update(order: @order)
    redirect_to ingredient_path(@ingredient, cart:"open")
  end

  def destroy

  end

  def near

  end

  private

  def find_ingredient
    @ingredient = Ingredient.find(params[:id])
    authorize @ingredient
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :photo, :unit_price, :expiry_date, :weight, :stock_amount, :unit, :discount_rate, :public_status, :description, :status, :price_cents)
  end
end

app/views/ingredients/index.html.erb
<%# Categories %>
<div class="categories">
  <div class="category nm-pink">Vegetarian</div>
  <div class="category nm-d-green">Vegan</div>
  <div class="category nm-green">Gluten free</div>
  <div class="category nm-orange">Lactose free</div>
  <div class="category nm-yellow">Fish</div>
  <div class="category nm-l-orange mr-0">Meat</div>
</div>
<%# Deals %>
<div class="monthly-deals">
  <div class="month p-0">
    <h2>September Deals</h2>
    <p>Exclusive deals for all Nomo customers,<br>
      starting from 1 - 30 Sep 2021</p>
  </div>
  <div class="d-flex">
    <%= image_tag "deal-03.svg", class: "mr-4" %>
    <%= image_tag "deal-4.svg" %>
  </div>
  <!-- </div> -->
</div>
<div class="d-flex">
  <div class="filter-col">
    <div class="filters">
      <h2>All ingredients</h2>
      <div class="sort">
        <p>Sort</p>
        <div class="radio-buttons">
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
            <label class="form-check-label promotion-item" for="flexRadioDefault1">
              Most popular
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label promotion-item" for="flexRadioDefault2">
              Location
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label promotion-item" for="flexRadioDefault2">
              Opening hours
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label promotion-item" for="flexRadioDefault2">
              Ratings
            </label>
          </div>
        </div>
      </div>
      <div class="expiry-date mb-4">
        <p>Price</p>
        <div class="d-flex">
          <div class="tag">$</div>
          <div class="tag">$$</div>
          <div class="tag">$$$</div>
          <div class="tag">$$$$</div>
        </div>
      </div>
      <div class="expiry-date">
        <p>Expiry date</p>
        <div class="radio-buttons">
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
            <label class="form-check-label promotion-item" for="flexRadioDefault1">
              Newest
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label promotion-item" for="flexRadioDefault2">
              Oldest
            </label>
          </div>
        </div>
      </div>
      <div class="promotion">
        <p>Promotion</p>
        <div class="radio-buttons">
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
            <label class="form-check-label promotion-item" for="flexRadioDefault1">
              5% off
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label promotion-item" for="flexRadioDefault2">
              10% off
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label promotion-item" for="flexRadioDefault2">
              15% off
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label" for="flexRadioDefault2">
              20% off
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input mr-2" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label promotion-item" for="flexRadioDefault2">
              50% off
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-9 ig-col">
    <div class="ingredients">
      <div class="section-ig-one">
        <h1 class="ig-header">Today's offers</h1>
        <div class="card-row">
          <!-- <div class="owl-carousel owl-theme"> -->
          <%#= @ingredients.each do |ingredient| %>
            <%= render partial: 'shared/card-ingredient', locals: { ingredients: @ingredients.first(6) } %>
            <%# end %>
            <!-- </div> -->
          </div>
        </div>
        <div class="section-ig-two">
          <h1 class="ig-header">Popular near you</h1>
          <div class="card-row">
            <!--      <div class="owl-carousel owl-theme"> -->
            <%#= @ingredients.each do |ingredient| %>
              <%= render partial: 'shared/card-ingredient', locals: { ingredients: @near_ingredients }%>
              <%# end %>
              <!-- </div> -->
            </div>
          </div>
          <div class="section-ig-three">
            <h1 class="ig-header">One last call</h1>
            <div class="card-row">
              <!-- <div class="owl-carousel owl-theme"> -->
              <%#= @ingredients.each do |ingredient| %>
                <%= render partial: 'shared/card-ingredient', locals: { ingredients: @expire_today_three_ing } %>
                <%# end %>
                <!--           </div> -->
              </div>
            </div>
            <div class="section-ig-fourth">
              <%= link_to "Show more", ingredients_path, class: "checkout-button"  %>
            </div>
          </div>
        </div>
      </div>
      <%= render 'shared/footer' %>

app/views/ingredients/my_ingredients.html.erb
<div class="dashboard">
  <%= render 'shared/dashboard_sidenav' %>
  <div class="dashboard-content-container">
    <% content_for :navbar, 'dashboard' %>
    <%# Content Navbar %>
    <div class="dashboard-topnav">
      <div class="top-nav">
        <div class="input-group">
          <%= image_tag "search.svg", class: "input-group-text" %>
          <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon1">
        </div>
        <div class="topnav-actions">
          <%= image_tag "noti.svg", class: "mr-3"%>
          <%# <%= render 'shared/dashboard_topnav' %>
          <%= image_tag "avatar-dashboard.svg"%>
        </div>
      </div>
    </div>
    <%# End Topnav %>
    <div class="dashboard-content">
      <div class="content-container">
        <%# Page header %>
        <div class="dashboard-page-header d-flex justify-content-between">
          <h1>All ingredients</h1>
          <div class="topnav-actions">
            <%# <button class="btn dashboard-button-white mr-2">Import</button> %>
            <%= link_to 'Import', "#", class: "dashboard-button dashboard-button-white mr-2" %>
            <%= link_to 'Add ingredient', new_ingredient_path, class: "dashboard-button" %>
          </div>
        </div>
        <%# Place your content below %>
        <%# Tab %>
        <ul class="nav nav-pills">
          <li class="active"><a data-toggle="pill" href="#all-ingredients">All</a></li>
          <li><a data-toggle="pill" href="#expired">Expired</a></li>
          <li><a data-toggle="pill" href="#sold">Sold</a></li>
        </ul>
        <%# Content %>
        <div class="tab-content">
          <%# All %>
          <div id="all-ingredients" class="tab-pane active">
            <table class="table table-light mt-4">
              <%= render 'shared/ingredient_table_head' %>
              <tbody>
                <% @ingredients.each do |ingredient| %>
                  <tr>
                    <td scope="row" class="pr-0"><input class="form-check-input" type="checkbox"></td>
                    <% if ingredient.photo.attached? %>
                      <td scope="row" class="pl-2 pr-0"><%= cl_image_tag ingredient.photo.key, width: 40, height: 40, crop: :fill %></td>
                    <% else %>
                      <td scope="row" class="pl-2 pr-0"><%= image_tag "ingredient_default.png", width: 40, height: 40, crop: :fill %></td>
                    <% end %>
                    <td scope="row">000<%= ingredient.id %></td>
                    <td scope="row"><%= ingredient.name %></td>
                    <td scope="row">$<%= ingredient.unit_price %></td>
                    <td scope="row"><%= ingredient.stock_amount %></td>
                    <td scope="row"><%= ingredient.unit %></td>
                    <td scope="row"><%= ingredient.discount_rate %>%</td>
                    <% if ingredient.expiry_date == Date.today %>
                      <td scope="row" style="color: #EE7246;">Today</td>
                      <td scope="row"><%= image_tag "alert.svg" %></td>
                    <% elsif ingredient.expiry_date == Date.tomorrow %>
                      <td scope="row" style="color: #EE7246;">Tomorrow</td>
                      <td scope="row"><%= image_tag "alert.svg" %></td>
                    <% else %>
                      <td scope="row"><%= change_date_format(ingredient.expiry_date) %></td>
                      <td scope="row"></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <%# Expired %>
          <div id="expired" class="tab-pane fade">
            <table class="table table-light mt-4">
              <%= render 'shared/ingredient_table_head' %>
              <tbody>
                <% @expired_ingredients.each do |ingredient| %>
                  <tr>
                    <td scope="row" class="pr-0"><input class="form-check-input" type="checkbox"></td>
                    <% if ingredient.photo.attached? %>
                      <td scope="row" class="pl-2 pr-0"><%= cl_image_tag ingredient.photo.key, width: 40, height: 40, crop: :fill %></td>
                    <% else %>
                      <td scope="row" class="pl-2 pr-0"><%= image_tag "ingredient_default.png", width: 40, height: 40, crop: :fill %></td>
                    <% end %>
                    <td scope="row">000<%= ingredient.id %></td>
                    <td scope="row"><%= ingredient.name %></td>
                    <td scope="row">$<%= ingredient.unit_price %></td>
                    <td scope="row"><%= ingredient.stock_amount %></td>
                    <td scope="row"><%= ingredient.unit %></td>
                    <td scope="row"><%= ingredient.discount_rate %>%</td>
                    <td scope="row"><%= change_date_format(ingredient.expiry_date) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <%# Sold %>
          <div id="sold" class="tab-pane fade">
            <table class="table table-light mt-4">
              <%= render 'shared/ingredient_table_head' %>
              <tbody>
                <% @sold_ingredients.each do |ingredient| %>
                  <tr>
                    <td scope="row" class="pr-0"><input class="form-check-input" type="checkbox"></td>
                    <% if ingredient.photo.attached? %>
                      <td scope="row" class="pl-2 pr-0"><%= cl_image_tag ingredient.photo.key, width: 40, height: 40, crop: :fill %></td>
                    <% else %>
                      <td scope="row" class="pl-2 pr-0"><%= image_tag "ingredient_default.png", width: 40, height: 40, crop: :fill %></td>
                    <% end %>
                    <td scope="row">000<%= ingredient.id %></td>
                    <td scope="row"><%= ingredient.name %></td>
                    <td scope="row">$<%= ingredient.unit_price %></td>
                    <td scope="row"><%= ingredient.stock_amount %></td>
                    <td scope="row"><%= ingredient.unit %></td>
                    <td scope="row"><%= ingredient.discount_rate %>%</td>
                    <td scope="row"><%= change_date_format(ingredient.expiry_date) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <%# Background End %>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="dashboard">
  <%= render 'shared/dashboard_sidenav' %>
  <div class="dashboard-content-container">
    <% content_for :navbar, 'dashboard' %>
    <%# Content Navbar %>
    <div class="dashboard-topnav">
      <div class="top-nav">
        <%# Search %>
        <div class="input-group">
          <%= image_tag "search.svg", class: "input-group-text" %>
          <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon1">
        </div>
        <div class="topnav-actions">
          <%= image_tag "noti.svg", class: "mr-3"%>
          <%# <%= render 'shared/dashboard_topnav' %>
          <%= image_tag "avatar-dashboard.svg"%>
        </div>
      </div>
    </div>
    <hr class="#">
    <%# End Topnav %>
    <div class="dashboard-content">
      <div class="content-container">
        <%# Page header %>
        <div class="dashboard-page-header d-flex justify-content-between">
          <h1>New ingredient</h1>
          <div class="topnav-actions">
            <%# <button class="btn dashboard-button-white mr-2">Import</button> %>
          </div>
        </div>
        <%# Place your content below %>
        <%= simple_form_for(@ingredient) do |f| %>
          <div class="dashboard-form-container">
            <%# Left panel %>
            <div class="dashboard-form-container-left">
              <div class="form-box">
                <h4 class="mb-4">Basic info</h4>
                <%= f.input :name, label: 'Ingredient name', placeholder: 'e.g. Apple, Banana,etc.', required: true  %>
                <%= f.input :description, placeholder: 'Tell us more about your ingredient...' %>
              </div>
              <div class="form-box">
                <h4>Expiry Date<span style="color:red;">*</span></h4>
                <%= f.input :expiry_date, as: :date, html5: true, label: false %>
                <% f.input :status, input_html: {value: 'unsold'} %>
                <% f.input :public_status, input_html: {value: 'available'} %>
              </div>
              <div class="form-box">
                <h4>Photo<span style="color:red;">*</span></h4>
                <%= f.input :photo, as: :file, label: false %>
              </div>
            </div>
            <%# Right panel %>
            <div class="dashboard-form-container-right">
              <div class="form-box">
                <h4>Pricing<span style="color:red;">*</span></h4>
                <%= f.input :unit_price,  as: :numeric, label: 'Unit price ($)', placeholder: '$', required: true %>
                <%= f.input :discount_rate, as: :numeric, label: 'Discount rate',placeholder: '%' %>
              </div>
              <div class="form-box">
                <h4>Inventory<span style="color:red;">*</span></h4>
                <%= f.input :unit, label: 'Stock unit', placeholder: 'e.g. kg, grams, etc. ', required: true %>
                <%= f.input :stock_amount, as: :numeric, label: 'Stock amount', required: true%>
              </div>
            </div>
          </div>
          <hr>
          <%= link_to "Cancel", my_ingredients_path, class: "btn", id: "cancel" %>
          <%= f.button :submit, "Create product", class: "dashboard-button-large" %>
        <% end %>
        <%# End of content %>
      </div>
    </div>
    <%# Background End %>
  </div>
</div>

app/views/ingredients/show.html.erb
<%# Left panel %>
<div class="left-pane" style="background-image: url('<%= cl_image_path @ingredient.photo.key %>')">
  <%# QTY + Add to cart %>
  <div class="qty-order">
    <div class="col-6 quantity margin-0">
      <p>QTY : </p>
      <p><%= @ingredient.stock_amount%> kg</p>
    </div>
    <div class="col-6 margin-0 order">
      <%= simple_form_for @ingredient do |f| %>
        <%= f.input :order_id, value: @order.id, as: :hidden, class: "nm-black mt-0" %>
        <%= f.submit 'Add to cart', class: 'order-btn'%>
      <% end %>
      <%= humanized_money_with_symbol(@ingredient.price * @ingredient.stock_amount) %>
    </div>
  </div>
</div>
<%# Right panel %>
<div class="right-pane">
  <%# First Section %>
  <div class=" section-one">
    <p class="resto-name"><%= @ingredient.seller.restaurant.name %></p>
    <h1 class="ingredient-header"><%= @ingredient.name %></h1>
    <div class="ingredients-badges">
      <span class="badge-round-yellow"><%= @ingredient.seller.restaurant.category.upcase %></span>
      <span class="badge-round-yellow bg-orange"><%= @ingredient.discount_rate %>% OFF</span>
    </div>
    <p class="ingredient-description"><%= @ingredient.description %></p>
    <div class="promo-cards">
      <%= render 'shared/card-l-green' %>
      <%= render 'shared/card-green' %>
      <%= render 'shared/card-d-green' %>
    </div>
    <hr>
  </div>
  <%# Restaurant info %>
  <div class="restaurant-info py-4">
    <div class="row">
      <div class="col-6">
        <p class="pickup-detail">Pickup details</p>
        <p class="detail-item "><strong>Opening hours: </strong><%= @ingredient.seller.restaurant.opening_hours %>AM - <%= @ingredient.seller.restaurant.closing_hours %>PM</p>
        <p class="detail-item"><strong>Store location: </strong><%= @ingredient.seller.restaurant.address %></p>
      </div>
      <div class="col-6">
        <div id="map"
      style="width: 100%; height: 200px;"
      data-markers="<%= @marker.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
  </div>
  <%# Matching recipe %>
  <div class="section-two">
    <h1 class="ingredient-header">Matching recipes</h1>
    <div class="cards-flex justify-content-between">
      <%= render 'shared/card-recipe' %>
    </div>
  </div>
  <%# Often pair with %>
  <div class="section-three">
    <h1 class="ingredient-header">Often paired with...</h1>
    <div class="cards-flex justify-content-between">
      <%= render partial: 'shared/show-card-ingredient', locals: { ingredients: @paired_ingredients } %>
    </div>
  </div>
  <%# Other product in this store %>
  <div class="section-four">
    <h1 class="ingredient-header">Other products in this store</h1>
    <div class="cards-flex justify-content-between">
      <%= render partial: 'shared/show-card-ingredient', locals: { ingredients: @seller_ingredients } %>
    </div>
  </div>
  <%# End of right panel %>
</div>